name: vita
description: vita

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  path_provider: ^2.0.12
  audio_session: ^0.1.13
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/medicine1.png
    - assets/medicine2.png
    - assets/medicine3.png
    - assets/medicine4.png
    - assets/vita-profile.png
    - assets/user-profile.png

flutter_intl:
  enabled: true
